Repository melkypie/resource-packs, pull requests merged in 2025-07, with the labels that each got.

#365 Tab/Fix Update
  bonds_pouch/arrow_left.png
  bonds_pouch/arrow_left_hovered.png
  bonds_pouch/arrow_right.png
  bonds_pouch/arrow_right_hovered.png
  bonds_pouch/bond.png
  icon.png
  other/minimap_orb_frame_small_flashing.png
  other/minimap_orb_run_activated.png
  other/stash_units_green_check_mark.png
  overrides.toml
  pack.properties
  tab/transparent_short_left_right_background.png
  tab/transparent_short_left_right_hovered.png
  tab/transparent_short_left_right_outline.png
  tab/transparent_short_left_right_outline_selected.png
  tab/transparent_short_middle_background.png
  tab/transparent_short_middle_hovered.png
  tab/transparent_short_middle_outline.png
  tab/transparent_short_middle_outline_selected.png
  tab/transparent_tall_left_right_background.png
  tab/transparent_tall_left_right_hovered.png
  tab/transparent_tall_left_right_outline.png
  tab/transparent_tall_left_right_outline_selected.png
  tab/transparent_tall_middle_background.png
  tab/transparent_tall_middle_hovered.png
  tab/transparent_tall_middle_outline.png
  tab/transparent_tall_middle_outline_selected.png
  welcome_screen/key.png
  welcome_screen/keyring.png
Labels: Pack: approved, Pack: updated, Pack: merged, Checks: passed

#363 Tab/Fix Update
  bonds_pouch/arrow_left.png
  bonds_pouch/arrow_left_hovered.png
  bonds_pouch/arrow_right.png
  bonds_pouch/arrow_right_hovered.png
  bonds_pouch/bond.png
  icon.png
  other/minimap_orb_frame_small_flashing.png
  other/minimap_orb_run_activated.png
  overrides.toml
  pack.properties
  tab/transparent_short_left_right_background.png
  tab/transparent_short_left_right_hovered.png
  tab/transparent_short_left_right_outline.png
  tab/transparent_short_left_right_outline_selected.png
  tab/transparent_short_middle_background.png
  tab/transparent_short_middle_hovered.png
  tab/transparent_short_middle_outline.png
  tab/transparent_short_middle_outline_selected.png
  tab/transparent_tall_left_right_background.png
  tab/transparent_tall_left_right_hovered.png
  tab/transparent_tall_left_right_outline.png
  tab/transparent_tall_left_right_outline_selected.png
  tab/transparent_tall_middle_background.png
  tab/transparent_tall_middle_hovered.png
  tab/transparent_tall_middle_outline.png
  tab/transparent_tall_middle_outline_selected.png
  welcome_screen/key.png
  welcome_screen/keyring.png
Labels: Pack: approved, Pack: updated, Checks: passed

#370 The Neverending Update... Update
  icon.png
  normal_spell/monster_inspect_disabled_resized.png
  normal_spell/monster_inspect_resized.png
Labels: Pack: approved, Pack: updated, Pack: merged, Checks: passed

#369 The Neverending Update... Update
  icon.png
  normal_spell/monster_inspect_disabled_resized.png
  normal_spell/monster_inspect_resized.png
Labels: Pack: approved, Pack: updated, Pack: merged, Checks: passed

#372 Added Monster Inspect
  normal_spell/monster_inspect.png
  normal_spell/monster_inspect_disabled.png
  normal_spell/monster_inspect_disabled_resized.png
  normal_spell/monster_inspect_resized.png
Labels: Pack: approved, Pack: updated, Pack: merged, Checks: passed, Checks: warning
